name = "UKrig"
uuid = "33fd7dbb-7ebc-4259-b98d-d32823368aee"
authors = ["Ethan Anderes"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
